# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448fd6e1141182e0a18fdb98c1fdc5a8aa7f93633c10336f361fc4a2ac9aeec69b2d44bf5e5f32dd246e4e0bdd92c8ebdb1e6db5f7495bb43d78ac807264b18b

test:
  secret_key_base: fe2925a02c899d7021a3f08eac40a8322f957f612b080ca25f022bd05c3d8821b195764a16b59a0130b812c5def08577a1e547435d491c2b23850eded01800be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
